### PR TITLE
Fixes deprecation alert when using symfony/error-handler

### LINKED ISSUE #701: Deprecations emitted by symfony/error-handler when loading Algolia classes
- Algolia Client Version: 3.2.0
- Language Version: 8.1

### Description

Running my test suite results in a lot of deprecations from Symfony, when loading Algolia classes:

```
  1x: Method "Psr\Http\Message\UriInterface::getScheme()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getAuthority()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getUserInfo()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getHost()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getPort()" might add "?int" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getPath()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getQuery()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::getFragment()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withScheme()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withUserInfo()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withHost()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withPort()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withPath()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withQuery()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\UriInterface::withFragment()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Uri" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::getRequestTarget()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::withRequestTarget()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::getMethod()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::withMethod()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::getUri()" might add "UriInterface" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\RequestInterface::withUri()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::getProtocolVersion()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::withProtocolVersion()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::getHeaders()" might add "array" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::hasHeader()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::getHeader()" might add "array" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::getHeaderLine()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::withHeader()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::withAddedHeader()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::withoutHeader()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::getBody()" might add "StreamInterface" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\MessageInterface::withBody()" might add "static" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Request" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::getContents()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::close()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::getSize()" might add "?int" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::isReadable()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::isWritable()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::isSeekable()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::eof()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::tell()" might add "int" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::read()" might add "string" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::write()" might add "int" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Psr\Http\Message\StreamInterface::getMetadata()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Http\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\BatchIndexingResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\BatchIndexingResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::key()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\BatchIndexingResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::valid()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\BatchIndexingResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\BatchIndexingResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Iterators\AbstractAlgoliaIterator" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Iterators\AbstractAlgoliaIterator" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AlgoliaGetAllModelsTest::testItGetsAllModelsFromTheIncludedFamilies from App\Tests\Integration\Algolia

  1x: Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application

  1x: Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application

  1x: Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application

  1x: Method "Iterator::key()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application

  1x: Method "Iterator::valid()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application

  1x: Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Algolia\AlgoliaSearch\Response\MultiResponse" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in ImportQueryRulesTest::testItImportsQueryRules from App\Tests\QueryRulesImport\Application
```

The messages say how this can be avoided.

### Steps To Reproduce

Write functional tests involving Algolia;setup `symfony/error-handler` in your project.

### PR DESCRIPTION
**Pull request by MarcBrillault**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no  
| BC breaks?        | no     
| Related Issue     | Fix #701 
| Need Doc update   | no

## Describe your change

Added PHPDoc @returns to some methods to prevent a deprecation alert when using symfony/error-handler

### CODE REVIEW

File: src/Http/Psr7/Request.php [hunk 1]
```diff
@@ -109,11 +121,17 @@ public function withMethod($method)
...
+    /**
+     * @return Uri|UriInterface|string
+     */
     public function getUri()
     {
         return $this->uri;
     }
 
+    /**
+     * @return $this|Request
```
Comment (greg0ire) [inline src/Http/Psr7/Request.php:133]: This seems redundant. IMO we assume tooling supports it and drop the right part, or we assume it does not and drop the left part.

**Review by damcou — APPROVED** [review]

**Comment by greg0ire** [comment]
Ping @damcou can we get this merged and released? :pray:

**Comment by damcou** [comment]
Hello @greg0ire ,
Sorry for the delay, I just merged it.
Regarding the release, we'll try to take a look at it at the beginning of this month (june), it's on our to-do list.

Thanks for understanding.

**Comment by greg0ire** [comment]
Thanks, looking forward to it!

**Comment by greg0ire** [comment]
ping @damcou :pray:

**Comment by damcou** [comment]
Hello @greg0ire 
I'm very sorry, I know we're late on this, but we had some other pressing priorities on some other topics in June :( 
We will do our best to release this week or next week, sorry again !

**Comment by damcou** [comment]
Hello @greg0ire 

The v3.3.0 has just been released, sorry again for the delay :( .

**Comment by greg0ire** [comment]
Thanks a lot!
