### PR TITLE
fix(personnalization-strategy): fixes flaky tests

### LINKED ISSUE #634: Implement retry until success for restore_api_key() call in CTS test
Because of the way Algolia is designed, performing a `restoreApiKey` may not
succeed because the previous `deleteApiKey` takes some time to get propagated
to all Algolia servers, giving us the following response: `[404] Key already
exists`.

To prevent that, we need to change the `testApiKeys` CTS test, if implemented,
to retry even on `[404] Key already exists` response.

### PR DESCRIPTION
**Pull request by chloelbn**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Need Doc update   | no

## Describe your change

Fixes tests to skip the 429 error

### CODE REVIEW

**Review by DevinCodes — APPROVED** [review]

File: tests/Integration/PersonalizationStrategyTest.php [hunk 1]
```diff
@@ -31,7 +31,13 @@ public function testPersonalizationStrategy()
             'personalizationImpact' => 0,
         );
 
-        $response = $recommendationClient->setPersonalizationStrategy($personalizationStrategy);
+        try {
+            $response = $recommendationClient->setPersonalizationStrategy($personalizationStrategy);
+        } catch (\Exception $e) {
```
Comment (DevinCodes) [inline tests/Integration/PersonalizationStrategyTest.php:36]: Can we catch an `AlgoliaException` here instead of the more generic `\Exception`?

**Review by DevinCodes — CHANGES_REQUESTED** [review]

**Review by DevinCodes — APPROVED** [review]

**Comment by DevinCodes** [comment]
Code looks good to me, so I approved ✅  
The CI is failing by the way, any idea why?

**Comment by chloelbn** [comment]
@DevinCodes fixed the issue!

**Review by DevinCodes — APPROVED** [review]
